---
- name: Pause for 60 seconds waiting couchDB running up
  tags: 'couchdb-cluster'
  pause: minutes=1

- name:  enable cluster
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ inventory_hostname }}:5984/_cluster_setup -d "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"admin\", \"password\":\"admin\", \"port\": \"5984\", \"node_count\": \"3\"}"'

# add harverster1 as slave database to dbServer(master db)
- name: prepare for adding "{{ harverster1 }}" into "{{ dbServer }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbServer }}:5984/_cluster_setup -d "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"admin\", \"password\":\"admin\", \"port\": \"5984\", \"remote_node\": \"{{ harverster1 }}\", \"remote_current_user\": \"admin\", \"remote_current_password\": \"admin\"}"'
  when: inventory_hostname == "{{ dbServer }}"

- name: add "{{ harverster1 }}" node into "{{ dbServer }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbServer }}:5984/_cluster_setup -d "{\"action\": \"add_node\", \"host\":\"{{ harverster1 }}\", \"port\": \"5984\", \"username\": \"admin\", \"password\":\"admin\"}"'
  when: inventory_hostname == "{{ dbServer }}"
 
# add harverster2 as slave database to dbServer(master db) 
- name: prepare for adding "{{ harverster2 }}" into "{{ dbServer }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbServer }}:5984/_cluster_setup -d "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"admin\", \"password\":\"admin\", \"port\": \"5984\", \"remote_node\": \"{{ harverster2 }}\", \"remote_current_user\": \"admin\", \"remote_current_password\": \"admin\"}"'
  when: inventory_hostname == "{{ dbServer }}"

- name: add "{{ harverster2 }}" node into "{{ dbServer }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbServer }}:5984/_cluster_setup -d "{\"action\": \"add_node\", \"host\":\"{{ harverster2 }}\", \"port\": \"5984\", \"username\": \"admin\", \"password\":\"admin\"}"'
  when: inventory_hostname == "{{ dbServer }}"

- name: finish cluster 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbServer }}:5984/_cluster_setup -d "{\"action\": \"finish_cluster\"}"'
  when: inventory_hostname == "{{ dbServer }}"
