---
- name: Uninstall old versions of couchdb
  tags: 'couchdb'
  become: yes
  apt:
    name: couchdb
    state: absent

- name: Create couchdb directory
  tags: 'couchdb'
  become: yes
  file:
    path: "{{ couchdb_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory
    
- name: Add couchdb apt repository key
  tags: 'couchdb'
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: Add couchdb apt repository and update apt cache
  tags: 'couchdb'
  become: yes
  apt_repository:
    repo: "deb https://apache.bintray.com/couchdb-deb bionic main"
    mode: '644'
    update_cache: yes
    state: present

- name: Install couchdb
  tags: 'couchdb'
  become: yes
  apt:
    name: couchdb
    state: latest
    install_recommends: no
    update_cache: yes

- name: ensure couchdb is at the latest version
  apt: name=couchdb state=latest

- name: Bind Node Address to Public
  become: yes
  lineinfile:
    dest: /opt/couchdb/etc/local.ini
    insertafter: '^\[chttpd\]$'
    line: 'bind_address = 0.0.0.0'

- name: add admin password
  become: yes
  lineinfile:
    dest: /opt/couchdb/etc/local.ini
    insertafter: '^\[admins]\]$'
    line: 'admin = admin'
    
- name: add hostname into /opt/couchdb/etc/vm.agrs
  become: yes
  replace:
    path: /opt/couchdb/etc/vm.args
    regexp: '^-name couchdb@.*$'
    replace: '-name couchdb@{{ inventory_hostname }}'
    backup: yes
    
#- name: modify database file dir in /opt/couchdb/etc/default.ini
#  become: yes
#  replace:
#    path: /opt/couchdb/etc/default.ini
#    regexp: '^database_dir = .*$'
#    replace: 'database_dir = {{ couchdb_file_dir }}'
#    backup: yes
    
#- name: modify database view index dir in /opt/couchdb/etc/default.ini
#  become: yes
#  replace:
#    path: /opt/couchdb/etc/default.ini
#    regexp: '^view_index_dir  = .*$'
#    replace: 'view_index_dir  = {{ couchdb_view_index_dir }}'
#    backup: yes

- name: Copy "{{ couchdb_sys_file }}" files
  become: yes
  copy:
    src: "{{ local_config_dir }}/{{ couchdb_sys_file }}"
    dest: "{{ couchdb_sys_dir }}/{{ couchdb_sys_file }}"
    owner: "root"
    group: "root"
    
- name: start couchdb
  become: yes
  service:
    name: couchdb
    state: restarted
