---
- name: Pause for 60 seconds waiting couchDB running up
  tags: 'couchdb-cluster'
  pause: minutes=1

- name:  enable cluster
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ inventory_hostname }}:5984/_cluster_setup -d "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"admin\", \"password\":\"admin\", \"port\": \"5984\", \"node_count\": \"3\"}"'

# add harvester1 as slave database to dbserver(master db)
- name: prepare for adding "{{ harvester1_addr }}" into "{{ dbserver_addr }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbserver_addr }}:5984/_cluster_setup -d "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"admin\", \"password\":\"admin\", \"port\": \"5984\", \"remote_node\": \"{{ harvester1_addr }}\", \"remote_current_user\": \"admin\", \"remote_current_password\": \"admin\"}"'
  when: inventory_hostname == "{{ dbserver_addr }}"

- name: add "{{ harvester1_addr }}" node into "{{ dbserver_addr }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbserver_addr }}:5984/_cluster_setup -d "{\"action\": \"add_node\", \"host\":\"{{ harvester1_addr }}\", \"port\": \"5984\", \"username\": \"admin\", \"password\":\"admin\"}"'
  when: inventory_hostname == "{{ dbserver_addr }}"
 
# add harvester2 as slave database to dbserver(master db) 
- name: prepare for adding "{{ harvester2_addr }}" into "{{ dbserver_addr }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbserver_addr }}:5984/_cluster_setup -d "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"admin\", \"password\":\"admin\", \"port\": \"5984\", \"remote_node\": \"{{ harvester2_addr }}\", \"remote_current_user\": \"admin\", \"remote_current_password\": \"admin\"}"'
  when: inventory_hostname == "{{ dbserver_addr }}"

- name: add "{{ harvester2_addr }}" node into "{{ dbserver_addr }}" 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbserver_addr }}:5984/_cluster_setup -d "{\"action\": \"add_node\", \"host\":\"{{ harvester2_addr }}\", \"port\": \"5984\", \"username\": \"admin\", \"password\":\"admin\"}"'
  when: inventory_hostname == "{{ dbserver_addr }}"

- name: finish cluster 
  tags: 'couchdb-cluster'
  become: yes
  shell: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@{{ dbserver_addr }}:5984/_cluster_setup -d "{\"action\": \"finish_cluster\"}"'
  when: inventory_hostname == "{{ dbserver_addr }}"
