---

- hosts: dbServer
  tasks:
    - name: copy python files to server
      copy:
        src: ../../aurin
        dest: /home/ubuntu
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: copy python files2 to server
      copy:
        src: ../../mapreduce
        dest: /home/ubuntu
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: copy python files to server
      copy:
        src: ../../geojson_data
        dest: /home/ubuntu
        mode: 0755
        owner: ubuntu
        group: ubuntu
    
    - name: Update apt
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
    
    - name: install python libraries
      pip:
        name: ['requests','couchdb']
        state: latest

    - name: run analyzer
      shell: bash execute.sh
      args:
        chdir: /home/ubuntu/mapreduce/