###################################################################################################################################
##Project: COMP90024--2020S1--Assignment2--Alcohol Tweets and Australian Cities Analytics on the Cloud
##Purpose:  to find out the correlations between alcohol-related tweets and demographic 
##          and behavioural characteristics in Australia cities.
##Team: group05-- Ruiqi Zhu (939162), Zhengyang Li (952972), Jianxin Xu (1014840), Qiuxia YIN (1017231), Fang Qu (1070888)
###################################################################################################################################

# . ./group05-openrc.sh; ansible-playbook -i ./inventory/hosts.ini -u ubuntu harvester_deploy.yml
---

- hosts: harverster1
  tasks:
    - name: copy python files to server
      copy:
        src: ../../harvester
        dest: /home/ubuntu
        mode: 0755
        owner: ubuntu
        group: ubuntu
    
    - name: copy ip list files to server
      copy:
        src: ../../deploy/config/generic.yaml
        dest: /home/ubuntu/harvester
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: Update apt
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
# apt-get upgrade; apt-get update
    - name: Install mpich
      become: yes
      apt:
        name: mpich
        state: latest

    - name: install python libraries
      pip:
        name: ['tweepy','couchdb','vaderSentiment','mpi4py','shapely']
        state: latest

    - name: run search api
      shell: bash run_harvester1.sh
      args:
        chdir: /home/ubuntu/harvester/
      register: is_api_run

    - name: display shell script result
      debug: msg="{{is_api_run.stdout}}"

- hosts: harverster2
  tasks:
    - name: copy app to server
      copy:
        src: ../../streaming
        dest: /home/ubuntu
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: start stream api
      shell: bash run.sh
      args:
        chdir: /home/ubuntu/streaming/
