###################################################################################################################################
##Project: COMP90024--2020S1--Assignment2--Alcohol Tweets and Australian Cities Analytics on the Cloud
##Purpose:  to find out the correlations between alcohol-related tweets and demographic 
##          and behavioural characteristics in Australia cities.
##Team: group05-- Ruiqi Zhu (939162), Zhengyang Li (952972), Jianxin Xu (1014840), Qiuxia YIN (1017231), Fang Qu (1070888)
###################################################################################################################################

# . ./openrc.sh; ansible-playbook -i ./inventory/hosts.ini -u ubuntu webserver_deploy.yml
---

- hosts: webServer
  vars_files: 
    - ../config/generic.yaml
  
  tasks:
    - name: copy python files to server
      copy:
        src: ../../web
        dest: /home/ubuntu
        mode: 0644
        owner: ubuntu
        group: ubuntu
        force: yes

    - name: copy ip list files to server
      copy:
        src: ../../deploy/config/generic.yaml
        dest: /home/ubuntu/web
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: Add proxy in /etc/environment
      become: yes
      lineinfile:
        dest: /etc/environment
        line: "{{ item }}"
      with_items:
        - 'HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/'
        - 'HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/'
        - 'http_proxy=http://wwwproxy.unimelb.edu.au:8000/'
        - 'https_proxy=http://wwwproxy.unimelb.edu.au:8000/'
        - 'no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au'

    - name: Reboot a machine
      become: yes
      reboot:
        reboot_timeout: 600

    - name: Update apt
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
# apt-get upgrade; apt-get update

    - name: Install dependencies
      become: yes
      apt:
        name: ['nginx', 'curl', 'git', 'python3-dev', 'net-tools','python3-pip', 'unzip', 'vim']
        state: latest

    - name: Update pip
      become: yes
      pip:
        name: ['pip']
        state: latest

    - name: copy config files to server
      copy:
        src: ../config/nginx.conf
        dest: /home/ubuntu/web/nginx.conf
        mode: 0644
        force: yes

    - name: copy nginx setting to server
      become: yes
      copy:
        src: ../config/default
        dest: /etc/nginx/sites-available/default
        mode: 0644
        force: yes

    - name: Add nginx setting to /etc/nginx/sites-available
      become: yes
      lineinfile:
        dest: /etc/nginx/sites-available/default
        line: "{{ item }}"
      with_items:
        - 'upstream flask {'
        - '    server {{ webServer }}:5000;'
        - '}'
        - 'server {'
        - '    listen 80; '
        - '    server_name localhost; '
        - '    location / {'
        - '        proxy_pass http://flask;'
        - '        proxy_set_header Host $host;'
        - '        proxy_set_header X-Real-IP $remote_addr;'
        - '    }}'

    - name: install python libraries
      pip:
        name: ['flask']
        state: latest

    - name: start nginx
      become: yes
      shell: nginx -c /home/ubuntu/web/nginx.conf
    
    - name: start web server
      become: yes
      shell: bash run.sh
      args:
        chdir: /home/ubuntu/web/


